Add new interface for adjust rz reg contents in some cases
rizinorg/rz-tracetest pull request #17
Opened 2023-06-29 02:32 UTC by Heersin

BAP-qemu frame represent register D17 as two S registers(S34, S35), while those S registers(S32/S33 ...) are not existed in rz_reg for arm32.
`dn` register can be represented as `concat(S_2n, S_2n+1)`, to get the correct d register value I need both two S register value in the for-loop of rz-tracetet
Currently my solution is to modify Adapter interface to support it. It  will affect other architecture's adapters, I am not sure it's a best practice.

2023-06-29 02:45 UTC, XVilka requested changes

2023-06-29 02:45 UTC, XVilka commented on rz-tracetest/adapter.cpp
> +			if (r.at(0) == 's') {
I suggest to put the the comment from the PR description here, right in the code, otherwise it would be hard to understand why it's needed

2023-06-29 05:48 UTC, thestr4ng3r commented on rz-tracetest/rzemu.cpp
> +			RzBitVector *extra = rz_reg_get_bv(reg.get(), ri);
I don't think it is a good idea to read register contents here. They might be undefined depending on what happened before.

2023-06-29 05:57 UTC, Rot127 approved these changes

2024-07-11 00:19 UTC, XVilka commented
What is the resolution with this? One year has passed.

2024-07-11 06:17 UTC, Rot127 commented
Is it still needed? If not I would vote for closing to keep the changes small.

2025-07-01 11:54 UTC, Rot127 commented
Close it for now.

2025-07-01 11:54 UTC, closed without merging