PPC trace adapter
rizinorg/rz-tracetest pull request #6
Opened 2022-07-31 22:11 UTC by Rot127

This PR adds the PPC Trace adapter. With it it brings several other needed additions.

- PPC trace adapter
- Allow to pass `mach` as additional parameter to `RizinBits()`.
- Adds the command line option `-b`. If it is set `rz_asm` is initialized in big endian mode.

2022-08-01 09:31 UTC, wargio commented on rz-tracetest/adapter.cpp
> +                        }
does not look like formatted

2022-08-01 09:31 UTC, wargio commented on rz-tracetest/adapter.cpp
> +                  }
same here.

2022-08-06 14:42 UTC, XVilka requested changes
I see also formatting changes here. Did you run `clang-format`? In that case, I recommend adding also a configuration here plus a simple CI action to check the formatting for any new PRs.

2022-08-06 14:42 UTC, XVilka commented on rz-tracetest/adapter.cpp
> +int TraceAdapter::RizinBits(std::optional<std::string> mode, std::optional<uint64_t> mach) const {
`mach` is `machine` right? Maybe write it as is then?

2022-08-06 14:42 UTC, XVilka commented on rz-tracetest/adapter.cpp
> +int TraceAdapter::RizinBits(std::optional<std::string> mode, std::optional<uint64_t> mach) const {
Maybe add a Doxygen too on what this function supposed to do

2022-08-06 18:28 UTC, Rot127 commented
> I see also formatting changes here. Did you run clang-format? In that case, I recommend adding also a configuration here plus a simple CI action to check the formatting for any new PRs.

Formatting was added here: https://github.com/rizinorg/rz-tracetest/pull/7
Would add the CI stuff in another PR.

2022-08-06 18:29 UTC, Rot127 commented
@XVilka What are the formatting changes you are talking about?

2022-08-07 07:15 UTC, thestr4ng3r commented
CI script seems a bit excessive to me since the commits happen rather rarely in here.

2022-08-07 07:17 UTC, thestr4ng3r requested changes
The commit referenced by the bap-frames submodule does not seem to exist in the currently used upstream bap repo. Where is it located at the moment?

2022-08-07 07:23 UTC, thestr4ng3r commented on rz-tracetest/adapter.cpp
> +			} else if (is_one_bit_flag(tracename)) {
`is_one_bit_flag` is only used here. It should be inlined imo.

2022-08-07 07:23 UTC, thestr4ng3r commented on rz-tracetest/adapter.h
> +		bool get_is_big_endian() { return this->big_endian; }
Use UpperCamelCase for method and function names please.

2022-08-07 07:23 UTC, thestr4ng3r commented on rz-tracetest/adapter.cpp
> + * \brief Returns the bits for asm.bits.
Documentation for a function should be only in a single place. I think for the TraceAdapter it should be in the header since these sources are just the stub implementations.

2022-08-07 14:40 UTC, XVilka commented
> @XVilka What are the formatting changes you are talking about?

Sorry, I can't see them now. Maybe it was my imagination or mixed with some other PR.

2022-08-08 13:12 UTC, XVilka approved these changes

2022-08-08 13:31 UTC, Rot127 commented
> The commit referenced by the bap-frames submodule does not seem to exist in the currently used upstream bap repo. Where is it located at the moment?

My bad. I added the PPC flags but forgot to open a pull request to BAP-frames.

2022-08-08 13:40 UTC, Rot127 commented
PR for bap-frames: https://github.com/BinaryAnalysisPlatform/bap-frames/pull/21

2022-08-09 13:58 UTC, wargio commented on rz-tracetest/adapter.cpp
> +				ut64 r = v & 0xfffffffffff3ffff;
remove the constant and use a `#define` to make it more clear.

2022-08-09 13:58 UTC, wargio commented on rz-tracetest/adapter.cpp
> +				ut64 r = v & 0xfffffffffff3ffff;
same above.

2022-08-09 22:03 UTC, wargio approved these changes

2022-08-10 09:08 UTC, thestr4ng3r approved these changes

2022-08-10 09:08 UTC, merged